# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d592eab6c1c9e2e78adf26b2fde9590aff229acb90c9101e069aab787c797d070a22cc5b7b30950985557598b0c31a088c0c8aeb14c7dce2065c416eaf950f93

test:
  secret_key_base: e24c0d6b57720a770a5a5c005220b190d64522351ab51a3c280155939963e4085d6d80421f817e540bc717944641d496a9a7fda2895e062c474532f4a1fcc6e4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
